### ISSUE TITLE
gdiw giving an error after a few other mods updated

### ISSUE THREAD

**Issue by kingarthur91** [DaCyclops/GDIW#17]
updated my mods today after the release of pyhightech and now gdiw throws an error that in data-final-fixes.lua.81 its unable to index a nil value

**Comment by funker** [comment]
I have the same issue. I didn't install PyHightech, but updated PyCoal and some other mods. 
Here is the list of mods that have been updated since the error appeared first:
![sshot-48](https://user-images.githubusercontent.com/3451013/38358430-7e7b7404-38c5-11e8-9566-e7f7cca36943.png)
Today some of the mods have been updated again.

I don't know if GDIW causes this or any of the other mods.

**Comment by DaCyclops** [comment]
FYI, latest updates include a number of changes to avoid issues as above.
