### ISSUE TITLE
Issue with pyhightech

### ISSUE THREAD

**Issue by TehFreek** [DaCyclops/GDIW#19]
When [Pyanodons HighTech](https://mods.factorio.com/mod/pyhightech) is enabled, GDIW fails to load with the following:

    __GDIW__/data-final-fixes.lua:130: attempt to index local 'rawResult' (a nil value)

**Comment by LovelySanta** [comment]
Hi,

This bug was also reported on my [MoreScience mod](https://mods.factorio.com/mod/MoreScience) in the [discussion tab](https://mods.factorio.com/mod/MoreScience/discussion/5b59cd2d1663f1000bd7dc91).

From a quick look into your code I think the issue is that you only look for recipe outcomes of types item, fluid or ammo. Science packs are tools. And my science packs require multiple input fluids and the resultType is tool as shown in the recipe [here](https://github.com/LovelySanta/FactorioMod-MoreScience/blob/master/prototypes/recipe/regular-science-pack.lua#L93-L108) and the tool prototype [here](https://github.com/LovelySanta/FactorioMod-MoreScience/blob/master/prototypes/item/regular-science-pack.lua#L31-L57).

Kind regards,
lovely_santa

**Comment by DaCyclops** [comment]
Updated code to work with MANY more types, and be cleaner.

Should be live in 0.16.3 and 0.17.2
