### ISSUE TITLE
Error on start up with the mod Factorio extended-core

### ISSUE THREAD

**Issue by Unifire1** [DaCyclops/GDIW#9]
i got an error with the mod factorio extended core while starting up the game and loading the prototypes i see following error appear:

error while loading recipe prototype "titanium-ore-GDIW-IR" (recipe): no such node (name) Modifications: GDIW

any suggestions to solve this?
thx Unifire

btw great mod works like a charm with other mods
PS link to the other mod: https://mods.factorio.com/mods/NathGamer/FactorioExtended-Core

**Comment by DaCyclops** [comment]
Thanks for the report.

Having a quick look at the code for FE-Core, it appears they use the shorthand method of defining a result (result="name" and result-count=#), and my code assumes all recipes it deals with use the longhand method (results={}) which is what vanilla fluid recipes use.

Might have to make some code to detect if that's happening...

**Comment by DaCyclops** [comment]
Actually, ended up being them using the short-hand version of Item Ingredients ({"iron-ore", 6}), and my code screwing it up when it attaches my temporary sortorder= variable, but doesnt remove it. I didnt do cleanup on that originally, because it was all ignored on almost every mod I tested on, since they all used long-form Ingredients.

Ive added cleanup for my sortorder variable, and tested it against FactorioExtended-Core,  incoming 0.14.12

**Comment by Unifire1** [comment]
wow thx for the super fast fix yeah i expected that something would be different @FE-core since a lot of other mods that i have work like a charm with GDIW.

I noticed there's only a small aesthetic error now with the recipe of titanium ore (R version) the icon shows concrete with danger patern with the R inside instead of the titanium ore icon with an R inside.

**Comment by DaCyclops** [comment]
Yeah, that's because I havn't had the chance to update the code to find those icons correctly (emergency bugfixes are possible while at work, but actual features are not :P)
